import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { AvaliationProvider } from "./contexts/avaliation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Art Cosplay - Concurso",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AvaliationProvider>{children}</AvaliationProvider>
      </body>
    </html>
  );
}
